### ISSUE TITLE
divide id nans

### ISSUE THREAD

**Issue by JordanLaserGit** [LynkerIntel/hfsubset#27]
There looks to be a few hundred divides that have a nan ids. Should these be removed or renamed somehow? 

This matters in the validation of an ngen-run folder, which is breaking when searching for forcing files corresponding to nan ids.

**Comment by program--** [comment]
I'll have to check what's causing the NaN IDs, but it may be from the hydrofabric itself. @mikejohnson51 Might have better intuition on the solution for this.

**Comment by mikejohnson51** [comment]
I'm out till Monday but suspect they are flowlines without catchment representations. So ID would != NA but divide_id == NA.

**Comment by JordanLaserGit** [comment]
Here's what I'm seeing. It's easy for me to put in a one liner to ignore these guys for my purposes. Figured I'd mention it just in case it's an unintended behavior of hfsubset. 

![Screenshot 2024-01-05 094620](https://github.com/LynkerIntel/hfsubset/assets/79336055/b269cb3c-fc2a-4e1d-9a73-8b77f5a46290)

**Comment by JordanLaserGit** [comment]
Switching to 'divide_id' from 'id' solved the problem. Thanks y'all.
